/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'addon-categories': AddonCategory;
    projects: Project;
    leads: Lead;
    'process-steps': ProcessStep;
    'before-after-cases': BeforeAfterCase;
    redirects: Redirect;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'addon-categories': AddonCategoriesSelect<false> | AddonCategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'process-steps': ProcessStepsSelect<false> | ProcessStepsSelect<true>;
    'before-after-cases': BeforeAfterCasesSelect<false> | BeforeAfterCasesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('it' | 'en' | 'fr' | 'ru' | 'de' | 'es')
    | ('it' | 'en' | 'fr' | 'ru' | 'de' | 'es')[];
  globals: {
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
    integrations: Integration;
    'site-copy': SiteCopy;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    'site-copy': SiteCopySelect<false> | SiteCopySelect<true>;
  };
  locale: 'it' | 'en' | 'fr' | 'ru' | 'de' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * owner: everything · editor: content · sales: leads only
   */
  role: 'owner' | 'editor' | 'sales';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  folder?: ('general' | 'projects' | 'services' | 'before-after' | 'brand') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Stable id matching pricing (e.g. premium-site)
   */
  serviceId: string;
  slug: string;
  sortOrder: number;
  icon: 'CalendarCheck' | 'Monitor' | 'RefreshCw' | 'Video' | 'Wrench';
  image?: (number | null) | Media;
  /**
   * Fallback public path (e.g. /images/service-….png) until media uploaded
   */
  imagePath?: string | null;
  published?: boolean | null;
  /**
   * EUR starting price
   */
  basePrice: number;
  isMonthly?: boolean | null;
  title: string;
  description: string;
  details?: string | null;
  whatYouGet?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  portfolioUrl?: string | null;
  portfolioLinkLabel?: string | null;
  portfolioUrl2?: string | null;
  portfolioLinkLabel2?: string | null;
  pricingSectionTitle?: string | null;
  pricingFootnote?: string | null;
  tiers?:
    | {
        tierId: string;
        price: number;
        monthly?: boolean | null;
        featured?: boolean | null;
        name: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addon-categories".
 */
export interface AddonCategory {
  id: number;
  categoryId: string;
  sortOrder: number;
  title: string;
  items: {
    itemId: string;
    label: string;
    info?: string | null;
    priceType?: ('from' | 'plus') | null;
    price?: number | null;
    enabled?: boolean | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  projectId: string;
  slug: string;
  /**
   * Display index e.g. 01
   */
  index: string;
  tag: string;
  sortOrder?: number | null;
  image?: (number | null) | Media;
  /**
   * Fallback /images/… path
   */
  imagePath?: string | null;
  imagePosition?: ('top' | 'center') | null;
  tech?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  url: string;
  displayUrl: string;
  isLive?: boolean | null;
  /**
   * Show on homepage Featured Work
   */
  featured?: boolean | null;
  published?: boolean | null;
  name: string;
  nameTagline?: string | null;
  subtitle: string;
  problem: string;
  solution: string;
  businessImpact: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | 'spam';
  priority?: ('low' | 'normal' | 'high') | null;
  fullName?: string | null;
  email: string;
  businessName?: string | null;
  businessType?: ('restaurant' | 'hotel' | 'bar' | 'other') | null;
  siteUrl?: string | null;
  brief?: string | null;
  source?: ('google' | 'referral' | 'social' | 'other') | null;
  intent?: ('audit' | 'contact') | null;
  locale?: ('it' | 'en' | 'fr' | 'ru' | 'de' | 'es') | null;
  selectedServices?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  selectedServiceSlugs?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  selectedAddons?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * EUR estimate from cart at submit time
   */
  estimatedTotal?: number | null;
  ip?: string | null;
  userAgent?: string | null;
  lostReason?: string | null;
  followUpAt?: string | null;
  assignee?: (number | null) | User;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  notes?:
    | {
        body: string;
        author?: (number | null) | User;
        createdAtNote?: string | null;
        id?: string | null;
      }[]
    | null;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps".
 */
export interface ProcessStep {
  id: number;
  stepId: string;
  number: string;
  sortOrder?: number | null;
  icon: 'Search' | 'Compass' | 'Brush' | 'Code2' | 'TrendingUp';
  title: string;
  summary?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after-cases".
 */
export interface BeforeAfterCase {
  id: number;
  caseId: string;
  sortOrder?: number | null;
  published?: boolean | null;
  beforeImage?: (number | null) | Media;
  afterImage?: (number | null) | Media;
  /**
   * Fallback path
   */
  beforeSrc?: string | null;
  /**
   * Fallback path
   */
  afterSrc?: string | null;
  tab?: string | null;
  headline?: string | null;
  changes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  beforeAlt?: string | null;
  afterAlt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * e.g. /work/old-slug or /en/work/old-slug
   */
  fromPath: string;
  toPath: string;
  /**
   * 301 if checked, else 302
   */
  permanent?: boolean | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: string;
  collection?: string | null;
  documentId?: string | null;
  summary?: string | null;
  actor?: (number | null) | User;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'addon-categories';
        value: number | AddonCategory;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'process-steps';
        value: number | ProcessStep;
      } | null)
    | ({
        relationTo: 'before-after-cases';
        value: number | BeforeAfterCase;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  serviceId?: T;
  slug?: T;
  sortOrder?: T;
  icon?: T;
  image?: T;
  imagePath?: T;
  published?: T;
  basePrice?: T;
  isMonthly?: T;
  title?: T;
  description?: T;
  details?: T;
  whatYouGet?:
    | T
    | {
        item?: T;
        id?: T;
      };
  portfolioUrl?: T;
  portfolioLinkLabel?: T;
  portfolioUrl2?: T;
  portfolioLinkLabel2?: T;
  pricingSectionTitle?: T;
  pricingFootnote?: T;
  tiers?:
    | T
    | {
        tierId?: T;
        price?: T;
        monthly?: T;
        featured?: T;
        name?: T;
        detail?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addon-categories_select".
 */
export interface AddonCategoriesSelect<T extends boolean = true> {
  categoryId?: T;
  sortOrder?: T;
  title?: T;
  items?:
    | T
    | {
        itemId?: T;
        label?: T;
        info?: T;
        priceType?: T;
        price?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  projectId?: T;
  slug?: T;
  index?: T;
  tag?: T;
  sortOrder?: T;
  image?: T;
  imagePath?: T;
  imagePosition?: T;
  tech?:
    | T
    | {
        label?: T;
        id?: T;
      };
  url?: T;
  displayUrl?: T;
  isLive?: T;
  featured?: T;
  published?: T;
  name?: T;
  nameTagline?: T;
  subtitle?: T;
  problem?: T;
  solution?: T;
  businessImpact?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  priority?: T;
  fullName?: T;
  email?: T;
  businessName?: T;
  businessType?: T;
  siteUrl?: T;
  brief?: T;
  source?: T;
  intent?: T;
  locale?: T;
  selectedServices?:
    | T
    | {
        value?: T;
        id?: T;
      };
  selectedServiceSlugs?:
    | T
    | {
        value?: T;
        id?: T;
      };
  selectedAddons?:
    | T
    | {
        value?: T;
        id?: T;
      };
  estimatedTotal?: T;
  ip?: T;
  userAgent?: T;
  lostReason?: T;
  followUpAt?: T;
  assignee?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  notes?:
    | T
    | {
        body?: T;
        author?: T;
        createdAtNote?: T;
        id?: T;
      };
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps_select".
 */
export interface ProcessStepsSelect<T extends boolean = true> {
  stepId?: T;
  number?: T;
  sortOrder?: T;
  icon?: T;
  title?: T;
  summary?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after-cases_select".
 */
export interface BeforeAfterCasesSelect<T extends boolean = true> {
  caseId?: T;
  sortOrder?: T;
  published?: T;
  beforeImage?: T;
  afterImage?: T;
  beforeSrc?: T;
  afterSrc?: T;
  tab?: T;
  headline?: T;
  changes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  beforeAlt?: T;
  afterAlt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  permanent?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collection?: T;
  documentId?: T;
  summary?: T;
  actor?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  brandTagline?: string | null;
  siteUrl: string;
  contactEmail: string;
  instagramUrl?: string | null;
  instagramBioLink?: string | null;
  footerLocation?: string | null;
  footerStatus?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  defaultTitle: string;
  defaultDescription: string;
  ogImage?: (number | null) | Media;
  ogImagePath?: string | null;
  organizationLogoPath?: string | null;
  /**
   * GA4 Measurement ID (G-…)
   */
  gaMeasurementId?: string | null;
  plausibleDomain?: string | null;
  metaPixelId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  /**
   * Set automatically from env (GMAIL_USER + GMAIL_APP_PASSWORD)
   */
  gmailConfigured?: boolean | null;
  /**
   * Set automatically from env (GOOGLE_SHEETS_*)
   */
  sheetsConfigured?: boolean | null;
  /**
   * Require Cloudflare Turnstile on contact form when site key is set
   */
  turnstileEnabled?: boolean | null;
  /**
   * GDPR retention hint (days). Soft-delete tooling uses this.
   */
  leadRetentionDays?: number | null;
  /**
   * Internal ops notes — secrets stay in env, never here
   */
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-copy".
 */
export interface SiteCopy {
  id: number;
  nav?: {
    work?: string | null;
    services?: string | null;
    process?: string | null;
    contact?: string | null;
    audit?: string | null;
    buy?: string | null;
    about?: string | null;
  };
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    subtitle?: string | null;
    lead?: string | null;
    primaryCta?: string | null;
    secondaryCta?: string | null;
    buyCta?: string | null;
    buyCtaShort?: string | null;
    socialProof?: string | null;
    mockupCaption?: string | null;
    chipHighlight?: string | null;
    chipAvailability?: string | null;
    chipAvailabilitySub?: string | null;
  };
  trust?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  proof?: {
    eyebrow?: string | null;
    items?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    footnote?: {
      value?: string | null;
      label?: string | null;
    };
  };
  problem?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  servicesLabel?: string | null;
  servicesLead?: string | null;
  caseStudies?: {
    label?: string | null;
    viewCaseStudy?: string | null;
    fields?: {
      problem?: string | null;
      solution?: string | null;
      businessImpact?: string | null;
    };
  };
  impact?: {
    label?: string | null;
    items?:
      | {
          title: string;
          body: string;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  audit?: {
    title?: string | null;
    body?: string | null;
    cta?: string | null;
    meta?: string | null;
    freeBadge?: string | null;
  };
  processSection?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    stepLabel?: string | null;
    footerNote?: string | null;
  };
  beforeAfter?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    beforeBadge?: string | null;
    afterBadge?: string | null;
    dragHint?: string | null;
    changesTitle?: string | null;
    footerNote?: string | null;
    showOnSite?: boolean | null;
  };
  about?: {
    eyebrow?: string | null;
    title?: string | null;
    bio?: string | null;
    pills?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  aboutPage?: {
    backToHome?: string | null;
  };
  contact?: {
    label?: string | null;
    title?: string | null;
    body?: string | null;
    compactTitle?: string | null;
    emailLabel?: string | null;
    whatsappLabel?: string | null;
    availability?: string | null;
  };
  orderPage?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    fromLabel?: string | null;
    plusLabel?: string | null;
    selectHint?: string | null;
    proceedCta?: string | null;
    footnote?: string | null;
    estimatedLabel?: string | null;
    addonsSectionTitle?: string | null;
    aboutServiceCta?: string | null;
  };
  pricingAddons?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    footnote?: string | null;
  };
  servicesPage?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    techStack?: string | null;
    viewAll?: string | null;
    pricingNote?: string | null;
  };
  servicePage?: {
    backToHome?: string | null;
    deliverables?: string | null;
    howItWorks?: string | null;
    viewService?: string | null;
    otherServices?: string | null;
    sectionEyebrow?: string | null;
    pricingEyebrow?: string | null;
    popularLabel?: string | null;
    orderCta?: string | null;
  };
  workPage?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    viewAll?: string | null;
    backToWork?: string | null;
    visitLiveSite?: string | null;
    liveStatus?: string | null;
    techStack?: string | null;
    overview?: string | null;
    otherProjects?: string | null;
  };
  footer?: {
    description?: string | null;
    links?: string | null;
    location?: string | null;
    status?: string | null;
    privacy?: string | null;
    built?: string | null;
  };
  privacyPage?: {
    title?: string | null;
    lastUpdated?: string | null;
    backToHome?: string | null;
    sections?:
      | {
          heading: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  langSelector?: {
    label?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandTagline?: T;
  siteUrl?: T;
  contactEmail?: T;
  instagramUrl?: T;
  instagramBioLink?: T;
  footerLocation?: T;
  footerStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  ogImage?: T;
  ogImagePath?: T;
  organizationLogoPath?: T;
  gaMeasurementId?: T;
  plausibleDomain?: T;
  metaPixelId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  gmailConfigured?: T;
  sheetsConfigured?: T;
  turnstileEnabled?: T;
  leadRetentionDays?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-copy_select".
 */
export interface SiteCopySelect<T extends boolean = true> {
  nav?:
    | T
    | {
        work?: T;
        services?: T;
        process?: T;
        contact?: T;
        audit?: T;
        buy?: T;
        about?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subtitle?: T;
        lead?: T;
        primaryCta?: T;
        secondaryCta?: T;
        buyCta?: T;
        buyCtaShort?: T;
        socialProof?: T;
        mockupCaption?: T;
        chipHighlight?: T;
        chipAvailability?: T;
        chipAvailabilitySub?: T;
      };
  trust?:
    | T
    | {
        item?: T;
        id?: T;
      };
  proof?:
    | T
    | {
        eyebrow?: T;
        items?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        footnote?:
          | T
          | {
              value?: T;
              label?: T;
            };
      };
  problem?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  servicesLabel?: T;
  servicesLead?: T;
  caseStudies?:
    | T
    | {
        label?: T;
        viewCaseStudy?: T;
        fields?:
          | T
          | {
              problem?: T;
              solution?: T;
              businessImpact?: T;
            };
      };
  impact?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              note?: T;
              id?: T;
            };
      };
  audit?:
    | T
    | {
        title?: T;
        body?: T;
        cta?: T;
        meta?: T;
        freeBadge?: T;
      };
  processSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        stepLabel?: T;
        footerNote?: T;
      };
  beforeAfter?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        beforeBadge?: T;
        afterBadge?: T;
        dragHint?: T;
        changesTitle?: T;
        footerNote?: T;
        showOnSite?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        bio?: T;
        pills?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  aboutPage?:
    | T
    | {
        backToHome?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        compactTitle?: T;
        emailLabel?: T;
        whatsappLabel?: T;
        availability?: T;
      };
  orderPage?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        fromLabel?: T;
        plusLabel?: T;
        selectHint?: T;
        proceedCta?: T;
        footnote?: T;
        estimatedLabel?: T;
        addonsSectionTitle?: T;
        aboutServiceCta?: T;
      };
  pricingAddons?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        footnote?: T;
      };
  servicesPage?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        techStack?: T;
        viewAll?: T;
        pricingNote?: T;
      };
  servicePage?:
    | T
    | {
        backToHome?: T;
        deliverables?: T;
        howItWorks?: T;
        viewService?: T;
        otherServices?: T;
        sectionEyebrow?: T;
        pricingEyebrow?: T;
        popularLabel?: T;
        orderCta?: T;
      };
  workPage?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        viewAll?: T;
        backToWork?: T;
        visitLiveSite?: T;
        liveStatus?: T;
        techStack?: T;
        overview?: T;
        otherProjects?: T;
      };
  footer?:
    | T
    | {
        description?: T;
        links?: T;
        location?: T;
        status?: T;
        privacy?: T;
        built?: T;
      };
  privacyPage?:
    | T
    | {
        title?: T;
        lastUpdated?: T;
        backToHome?: T;
        sections?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
            };
      };
  langSelector?:
    | T
    | {
        label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}