import type { HqResource } from "./resource-api";
import {
  BILLING_INTERVALS,
  INVOICE_STATUSES,
  MILESTONE_STATUSES,
  PROJECT_HEALTH_VALUES,
  PROJECT_PRIORITIES,
  PROJECT_STATUSES,
  SUBSCRIPTION_STATUSES,
} from "./enums";

const financeRead = "reports.read" as const;
const financeWrite = "finance.manage" as const;
const deliveryRead = "projects.read" as const;
const deliveryWrite = "projects.manage" as const;

export const clientProjectResource: HqResource = {
  table: "client_projects",
  singular: "client_project",
  readCapability: deliveryRead,
  writeCapability: deliveryWrite,
  orderBy: "updated_at",
  filters: { companyId: "company_id", dealId: "deal_id", status: "status", health: "health", ownerId: "owner_id" },
  searchColumns: ["name", "description"],
  listSelect: "id,name,company_id,deal_id,product_id,status,health,progress,target_date,sold_price,actual_hours,internal_hourly_cost,currency,updated_at,companies(id,name)",
  select: "*, companies(id,name), deals(id,title), contacts(id,first_name,last_name), products(id,name), project_milestones(*), tasks(*), activities(*), notes(*)",
  fields: [
    { input: "dealId", column: "deal_id", kind: "uuid", nullable: true },
    { input: "companyId", column: "company_id", kind: "uuid", nullable: true },
    { input: "primaryContactId", column: "primary_contact_id", kind: "uuid", nullable: true },
    { input: "productId", column: "product_id", kind: "uuid", nullable: true },
    { input: "caseId", column: "case_id", kind: "uuid", nullable: true },
    { input: "name", column: "name", kind: "string", required: true, maxLength: 300 },
    { input: "description", column: "description", kind: "string", nullable: true, maxLength: 10000 },
    { input: "status", column: "status", kind: "string", values: PROJECT_STATUSES, fallback: "planned" },
    { input: "health", column: "health", kind: "string", values: PROJECT_HEALTH_VALUES, fallback: "unknown" },
    { input: "priority", column: "priority", kind: "string", values: PROJECT_PRIORITIES, fallback: "normal" },
    { input: "ownerId", column: "owner_id", kind: "uuid", nullable: true },
    { input: "startDate", column: "start_date", kind: "date", nullable: true },
    { input: "targetDate", column: "target_date", kind: "date", nullable: true },
    { input: "completedAt", column: "completed_at", kind: "datetime", nullable: true },
    { input: "budget", column: "budget", kind: "decimal", fallback: "0" },
    { input: "soldPrice", column: "sold_price", kind: "decimal", fallback: "0" },
    { input: "estimatedHours", column: "estimated_hours", kind: "decimal", fallback: "0" },
    { input: "actualHours", column: "actual_hours", kind: "decimal", fallback: "0" },
    { input: "internalHourlyCost", column: "internal_hourly_cost", kind: "decimal", fallback: "0" },
    { input: "currency", column: "currency", kind: "string", maxLength: 3, fallback: "EUR" },
    { input: "progress", column: "progress", kind: "integer", min: 0, max: 100, fallback: 0 },
    { input: "metadata", column: "metadata", kind: "object", fallback: {} },
  ],
};

export const milestoneResource: HqResource = {
  table: "project_milestones",
  singular: "project_milestone",
  readCapability: deliveryRead,
  writeCapability: deliveryWrite,
  orderBy: "sort_order",
  filters: { projectId: "project_id", status: "status", ownerId: "owner_id" },
  fields: [
    { input: "projectId", column: "project_id", kind: "uuid", required: true },
    { input: "title", column: "title", kind: "string", required: true, maxLength: 300 },
    { input: "description", column: "description", kind: "string", nullable: true, maxLength: 10000 },
    { input: "status", column: "status", kind: "string", values: MILESTONE_STATUSES, fallback: "pending" },
    { input: "dueDate", column: "due_date", kind: "date", nullable: true },
    { input: "completedAt", column: "completed_at", kind: "datetime", nullable: true },
    { input: "amount", column: "amount", kind: "decimal", nullable: true },
    { input: "currency", column: "currency", kind: "string", maxLength: 3, fallback: "EUR" },
    { input: "sortOrder", column: "sort_order", kind: "integer", min: 0, max: 100000, fallback: 0 },
    { input: "ownerId", column: "owner_id", kind: "uuid", nullable: true },
  ],
};

export const invoiceResource: HqResource = {
  table: "invoices",
  singular: "invoice",
  readCapability: financeRead,
  writeCapability: financeWrite,
  orderBy: "issue_date",
  filters: { companyId: "company_id", projectId: "project_id", dealId: "deal_id", status: "status" },
  searchColumns: ["invoice_number", "notes"],
  select: "*, invoice_items(*), companies(id,name), client_projects(id,name)",
  listSelect: "id,invoice_number,company_id,project_id,status,currency,issue_date,due_date,total,amount_paid,remaining_amount,companies(id,name)",
  fields: [
    { input: "invoiceNumber", column: "invoice_number", kind: "string", required: true, maxLength: 100 },
    { input: "companyId", column: "company_id", kind: "uuid", required: true },
    { input: "contactId", column: "contact_id", kind: "uuid", nullable: true },
    { input: "projectId", column: "project_id", kind: "uuid", nullable: true },
    { input: "dealId", column: "deal_id", kind: "uuid", nullable: true },
    { input: "status", column: "status", kind: "string", values: INVOICE_STATUSES, fallback: "draft" },
    { input: "currency", column: "currency", kind: "string", maxLength: 3, fallback: "EUR" },
    { input: "issueDate", column: "issue_date", kind: "date", required: true },
    { input: "dueDate", column: "due_date", kind: "date", nullable: true },
    { input: "subtotal", column: "subtotal", kind: "decimal", fallback: "0" },
    { input: "taxTotal", column: "tax_total", kind: "decimal", fallback: "0" },
    { input: "discountTotal", column: "discount_total", kind: "decimal", fallback: "0" },
    { input: "total", column: "total", kind: "decimal", fallback: "0" },
    { input: "notes", column: "notes", kind: "string", nullable: true, maxLength: 10000 },
    { input: "metadata", column: "metadata", kind: "object", fallback: {} },
  ],
};

export const subscriptionResource: HqResource = {
  table: "subscriptions",
  singular: "subscription",
  readCapability: financeRead,
  writeCapability: financeWrite,
  filters: { companyId: "company_id", projectId: "project_id", productId: "product_id", status: "status" },
  select: "*, companies(id,name), products(id,name), client_projects(id,name)",
  listSelect: "id,name,company_id,product_id,status,amount,currency,interval,started_on,next_billing_date,companies(id,name),products(id,name)",
  fields: [
    { input: "name", column: "name", kind: "string", required: true, maxLength: 300 },
    { input: "companyId", column: "company_id", kind: "uuid", required: true },
    { input: "contactId", column: "contact_id", kind: "uuid", nullable: true },
    { input: "productId", column: "product_id", kind: "uuid", nullable: true },
    { input: "projectId", column: "project_id", kind: "uuid", nullable: true },
    { input: "status", column: "status", kind: "string", values: SUBSCRIPTION_STATUSES, fallback: "active" },
    { input: "amount", column: "amount", kind: "decimal", required: true },
    { input: "currency", column: "currency", kind: "string", maxLength: 3, fallback: "EUR" },
    { input: "interval", column: "interval", kind: "string", values: BILLING_INTERVALS, fallback: "month" },
    { input: "intervalCount", column: "interval_count", kind: "integer", min: 1, max: 120, fallback: 1 },
    { input: "startedOn", column: "started_on", kind: "date", required: true },
    { input: "currentPeriodStart", column: "current_period_start", kind: "date", nullable: true },
    { input: "currentPeriodEnd", column: "current_period_end", kind: "date", nullable: true },
    { input: "nextBillingDate", column: "next_billing_date", kind: "date", nullable: true },
    { input: "cancelledAt", column: "cancelled_at", kind: "datetime", nullable: true },
    { input: "externalReference", column: "external_reference", kind: "string", nullable: true, maxLength: 300 },
    { input: "metadata", column: "metadata", kind: "object", fallback: {} },
  ],
};
