-- Lead workspace: assignee, SLA timestamps, append-only lead_events

alter table public.leads
  add column if not exists assignee_id uuid references public.profiles(id) on delete set null,
  add column if not exists first_responded_at timestamptz,
  add column if not exists next_action_at timestamptz,
  add column if not exists qualified_at timestamptz,
  add column if not exists closed_at timestamptz,
  add column if not exists lost_reason text;

create index if not exists leads_status_created_idx
  on public.leads (status, created_at desc);

create index if not exists leads_assignee_status_idx
  on public.leads (assignee_id, status)
  where assignee_id is not null;

create index if not exists leads_next_action_idx
  on public.leads (next_action_at)
  where next_action_at is not null
    and status in ('new', 'in_progress');

create table if not exists public.lead_events (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.leads(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists lead_events_lead_idx
  on public.lead_events (lead_id, created_at desc);

create or replace function public.prevent_lead_event_mutation()
returns trigger language plpgsql as $$
begin
  if pg_trigger_depth() > 1 then
    return old;
  end if;
  raise exception 'lead_events is append-only';
end;
$$;

drop trigger if exists lead_events_append_only on public.lead_events;
create trigger lead_events_append_only
before update or delete on public.lead_events
for each row execute function public.prevent_lead_event_mutation();

alter table public.lead_events enable row level security;
