-- DormUp HQ Phase 1
-- Additive business operations schema. Existing CMS/CRM tables and data are preserved.

create extension if not exists "pgcrypto";

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null check (btrim(name) <> ''),
  legal_name text,
  tax_id text,
  email text,
  phone text,
  website text,
  address jsonb not null default '{}'::jsonb,
  status text not null default 'prospect' check (status in ('prospect', 'active', 'inactive')),
  owner_id uuid references public.profiles(id) on delete set null,
  tags text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete set null,
  first_name text,
  last_name text,
  email text,
  phone text,
  job_title text,
  is_primary boolean not null default false,
  status text not null default 'active' check (status in ('active', 'inactive')),
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    nullif(btrim(coalesce(first_name, '')), '') is not null
    or nullif(btrim(coalesce(last_name, '')), '') is not null
    or nullif(btrim(coalesce(email, '')), '') is not null
  )
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  sku text not null unique check (btrim(sku) <> ''),
  name text not null check (btrim(name) <> ''),
  description text,
  kind text not null default 'service' check (kind in ('service', 'subscription', 'addon', 'other')),
  unit text not null default 'item',
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  tax_rate numeric(7,4) not null default 0 check (tax_rate >= 0 and tax_rate <= 100),
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deals (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete set null,
  primary_contact_id uuid references public.contacts(id) on delete set null,
  lead_id uuid unique references public.leads(id) on delete set null,
  title text not null check (btrim(title) <> ''),
  stage text not null default 'qualified'
    check (stage in ('qualified', 'discovery', 'proposal', 'negotiation', 'won', 'lost')),
  status text not null default 'open' check (status in ('open', 'won', 'lost')),
  value numeric(14,2) not null default 0 check (value >= 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  probability smallint not null default 25 check (probability between 0 and 100),
  expected_close_date date,
  closed_at timestamptz,
  lost_reason text,
  owner_id uuid references public.profiles(id) on delete set null,
  source text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'open' and stage not in ('won', 'lost'))
    or (status = 'won' and stage = 'won')
    or (status = 'lost' and stage = 'lost')
  )
);

create table if not exists public.client_projects (
  id uuid primary key default gen_random_uuid(),
  project_number bigint generated by default as identity unique,
  deal_id uuid unique references public.deals(id) on delete set null,
  company_id uuid references public.companies(id) on delete set null,
  primary_contact_id uuid references public.contacts(id) on delete set null,
  case_id uuid unique references public.cases(id) on delete set null,
  name text not null check (btrim(name) <> ''),
  status text not null default 'planned'
    check (status in ('planned', 'active', 'on_hold', 'completed', 'cancelled')),
  health text not null default 'unknown'
    check (health in ('unknown', 'on_track', 'at_risk', 'off_track')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  owner_id uuid references public.profiles(id) on delete set null,
  start_date date,
  target_date date,
  completed_at timestamptz,
  budget numeric(14,2) not null default 0 check (budget >= 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  progress smallint not null default 0 check (progress between 0 and 100),
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (target_date is null or start_date is null or target_date >= start_date)
);

create table if not exists public.project_milestones (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.client_projects(id) on delete cascade,
  title text not null check (btrim(title) <> ''),
  description text,
  status text not null default 'pending'
    check (status in ('pending', 'in_progress', 'completed', 'blocked', 'cancelled')),
  due_date date,
  completed_at timestamptz,
  amount numeric(14,2) check (amount is null or amount >= 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  sort_order integer not null default 0,
  owner_id uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique check (btrim(invoice_number) <> ''),
  company_id uuid not null references public.companies(id) on delete restrict,
  contact_id uuid references public.contacts(id) on delete set null,
  project_id uuid references public.client_projects(id) on delete set null,
  deal_id uuid references public.deals(id) on delete set null,
  status text not null default 'draft'
    check (status in ('draft', 'sent', 'partially_paid', 'paid', 'overdue', 'void')),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  issue_date date not null default current_date,
  due_date date,
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  tax_total numeric(14,2) not null default 0 check (tax_total >= 0),
  discount_total numeric(14,2) not null default 0 check (discount_total >= 0),
  total numeric(14,2) not null default 0 check (total >= 0),
  amount_paid numeric(14,2) not null default 0 check (amount_paid >= 0),
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (due_date is null or due_date >= issue_date),
  check (amount_paid <= total)
);

create table if not exists public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  description text not null check (btrim(description) <> ''),
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  tax_rate numeric(7,4) not null default 0 check (tax_rate >= 0 and tax_rate <= 100),
  discount numeric(14,2) not null default 0 check (discount >= 0),
  line_subtotal numeric(14,2) not null default 0 check (line_subtotal >= 0),
  line_tax numeric(14,2) not null default 0 check (line_tax >= 0),
  line_total numeric(14,2) not null default 0 check (line_total >= 0),
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid references public.invoices(id) on delete set null,
  company_id uuid not null references public.companies(id) on delete restrict,
  amount numeric(14,2) not null check (amount > 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  status text not null default 'pending'
    check (status in ('pending', 'succeeded', 'failed', 'refunded', 'cancelled')),
  method text,
  external_reference text,
  paid_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete restrict,
  contact_id uuid references public.contacts(id) on delete set null,
  product_id uuid references public.products(id) on delete set null,
  project_id uuid references public.client_projects(id) on delete set null,
  status text not null default 'active'
    check (status in ('trialing', 'active', 'paused', 'past_due', 'cancelled', 'ended')),
  amount numeric(14,2) not null check (amount >= 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  interval text not null default 'month' check (interval in ('week', 'month', 'quarter', 'year')),
  interval_count integer not null default 1 check (interval_count > 0),
  started_on date not null default current_date,
  current_period_start date,
  current_period_end date,
  next_billing_date date,
  cancelled_at timestamptz,
  external_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    current_period_end is null
    or current_period_start is null
    or current_period_end >= current_period_start
  )
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  activity_type text not null
    check (activity_type in ('call', 'email', 'meeting', 'task', 'note', 'status_change', 'system', 'other')),
  subject text not null check (btrim(subject) <> ''),
  body text,
  company_id uuid references public.companies(id) on delete set null,
  contact_id uuid references public.contacts(id) on delete set null,
  deal_id uuid references public.deals(id) on delete set null,
  project_id uuid references public.client_projects(id) on delete set null,
  lead_id uuid references public.leads(id) on delete set null,
  task_id uuid references public.tasks(id) on delete set null,
  actor_id uuid references public.profiles(id) on delete set null,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (
    company_id is not null or contact_id is not null or deal_id is not null
    or project_id is not null or lead_id is not null or task_id is not null
  )
);

create table if not exists public.notes (
  id uuid primary key default gen_random_uuid(),
  body text not null check (btrim(body) <> ''),
  company_id uuid references public.companies(id) on delete cascade,
  contact_id uuid references public.contacts(id) on delete cascade,
  deal_id uuid references public.deals(id) on delete cascade,
  project_id uuid references public.client_projects(id) on delete cascade,
  lead_id uuid references public.leads(id) on delete cascade,
  task_id uuid references public.tasks(id) on delete cascade,
  author_id uuid references public.profiles(id) on delete set null,
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (num_nonnulls(company_id, contact_id, deal_id, project_id, lead_id, task_id) = 1)
);

create table if not exists public.attachments (
  id uuid primary key default gen_random_uuid(),
  bucket text not null default 'crm-private',
  path text not null unique check (btrim(path) <> ''),
  file_name text not null check (btrim(file_name) <> ''),
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  company_id uuid references public.companies(id) on delete cascade,
  contact_id uuid references public.contacts(id) on delete cascade,
  deal_id uuid references public.deals(id) on delete cascade,
  project_id uuid references public.client_projects(id) on delete cascade,
  invoice_id uuid references public.invoices(id) on delete cascade,
  activity_id bigint references public.activities(id) on delete cascade,
  uploaded_by uuid references public.profiles(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (num_nonnulls(company_id, contact_id, deal_id, project_id, invoice_id, activity_id) = 1)
);

-- Additive links from the existing lead/task workspaces into HQ.
alter table public.leads
  add column if not exists company_id uuid references public.companies(id) on delete set null,
  add column if not exists contact_id uuid references public.contacts(id) on delete set null,
  add column if not exists converted_deal_id uuid references public.deals(id) on delete set null,
  add column if not exists converted_at timestamptz,
  add column if not exists estimated_value numeric(14,2),
  add column if not exists currency text not null default 'EUR';

alter table public.tasks
  add column if not exists client_project_id uuid references public.client_projects(id) on delete cascade,
  add column if not exists deal_id uuid references public.deals(id) on delete set null,
  add column if not exists company_id uuid references public.companies(id) on delete set null,
  add column if not exists contact_id uuid references public.contacts(id) on delete set null,
  add column if not exists estimated_minutes integer,
  add column if not exists actual_minutes integer,
  add column if not exists billable boolean not null default false;

-- V1 domain expansion. These columns deliberately coexist with the compact
-- foundation above so the migration is safe when resumed after a partial run.
alter table public.companies
  add column if not exists industry text,
  add column if not exists city text,
  add column if not exists country text,
  add column if not exists internal_summary text;
alter table public.companies drop constraint if exists companies_status_check;
alter table public.companies add constraint companies_status_check
  check (status in ('prospect', 'active_client', 'inactive', 'former_client', 'partner')) not valid;
update public.companies set status = 'active_client' where status = 'active';
alter table public.companies validate constraint companies_status_check;

alter table public.contacts
  add column if not exists role text,
  add column if not exists whatsapp text,
  add column if not exists telegram text,
  add column if not exists preferred_language text;

alter table public.products
  add column if not exists category text,
  add column if not exists base_price numeric(14,2),
  add column if not exists max_price numeric(14,2),
  add column if not exists default_monthly_fee numeric(14,2),
  add column if not exists status text not null default 'active';
alter table public.products drop constraint if exists products_price_range_check;
alter table public.products add constraint products_price_range_check
  check (base_price is null or max_price is null or max_price >= base_price) not valid;
alter table public.products drop constraint if exists products_status_check;
alter table public.products add constraint products_status_check
  check (status in ('active', 'inactive', 'archived')) not valid;
alter table public.products validate constraint products_price_range_check;
alter table public.products validate constraint products_status_check;

alter table public.deals
  add column if not exists product_id uuid references public.products(id) on delete set null,
  add column if not exists pain_summary text,
  add column if not exists solution_summary text,
  add column if not exists proposal_amount numeric(14,2),
  add column if not exists setup_fee numeric(14,2),
  add column if not exists monthly_fee numeric(14,2),
  add column if not exists objections text,
  add column if not exists competitors text,
  add column if not exists next_action text,
  add column if not exists next_action_date date;

alter table public.client_projects
  add column if not exists product_id uuid references public.products(id) on delete set null,
  add column if not exists sold_price numeric(14,2) not null default 0,
  add column if not exists estimated_hours numeric(10,2) not null default 0,
  add column if not exists actual_hours numeric(10,2) not null default 0,
  add column if not exists internal_hourly_cost numeric(12,2) not null default 0,
  add column if not exists estimated_cost numeric(14,2)
    generated always as (estimated_hours * internal_hourly_cost) stored,
  add column if not exists actual_cost numeric(14,2)
    generated always as (actual_hours * internal_hourly_cost) stored,
  add column if not exists gross_profit numeric(14,2)
    generated always as (sold_price - (actual_hours * internal_hourly_cost)) stored,
  add column if not exists gross_margin numeric(9,4)
    generated always as (
      case when sold_price = 0 then 0
      else (sold_price - (actual_hours * internal_hourly_cost)) / sold_price * 100 end
    ) stored;
alter table public.client_projects drop constraint if exists client_projects_status_check;
alter table public.client_projects add constraint client_projects_status_check
  check (status in ('planned', 'discovery', 'design', 'development', 'testing', 'waiting_client', 'launch', 'completed', 'paused', 'cancelled')) not valid;
update public.client_projects set status = 'development' where status = 'active';
update public.client_projects set status = 'paused' where status = 'on_hold';
alter table public.client_projects validate constraint client_projects_status_check;
alter table public.client_projects drop constraint if exists client_projects_health_check;
alter table public.client_projects add constraint client_projects_health_check
  check (health in ('green', 'yellow', 'red', 'unknown')) not valid;
update public.client_projects set health = case health
  when 'on_track' then 'green' when 'at_risk' then 'yellow'
  when 'off_track' then 'red' else health end;
alter table public.client_projects validate constraint client_projects_health_check;

alter table public.invoices
  add column if not exists remaining_amount numeric(14,2)
    generated always as (greatest(total - amount_paid, 0)) stored;
alter table public.invoices drop constraint if exists invoices_status_check;
alter table public.invoices add constraint invoices_status_check
  check (status in ('draft', 'sent', 'viewed', 'partially_paid', 'paid', 'overdue', 'cancelled', 'void')) not valid;
alter table public.invoices validate constraint invoices_status_check;

alter table public.subscriptions
  add column if not exists name text;
update public.subscriptions set name = 'Recurring service' where name is null;
alter table public.subscriptions alter column name set not null;

alter table public.activities
  add column if not exists channel text,
  add column if not exists direction text,
  add column if not exists status text;

alter table public.leads
  add column if not exists category text,
  add column if not exists city text,
  add column if not exists country text,
  add column if not exists website text,
  add column if not exists instagram text,
  add column if not exists linkedin text,
  add column if not exists phone text,
  add column if not exists contact_person text,
  add column if not exists contact_role text,
  add column if not exists preferred_language text,
  add column if not exists lead_score smallint,
  add column if not exists estimated_employees integer,
  add column if not exists estimated_revenue numeric(14,2),
  add column if not exists instagram_followers integer,
  add column if not exists digital_maturity smallint,
  add column if not exists pain_score smallint,
  add column if not exists ability_to_pay smallint,
  add column if not exists willingness_to_pay smallint,
  add column if not exists urgency_score smallint,
  add column if not exists reachability_score smallint,
  add column if not exists estimated_deal_value numeric(14,2),
  add column if not exists recommended_offer text,
  add column if not exists notes text,
  add column if not exists last_contact_at timestamptz,
  add column if not exists next_follow_up_at timestamptz,
  add column if not exists current_tools text[],
  add column if not exists possible_pain text,
  add column if not exists potential_financial_gain numeric(14,2),
  add column if not exists recommended_price numeric(14,2);
alter table public.leads drop constraint if exists leads_status_check;
alter table public.leads add constraint leads_status_check
  check (status in ('new', 'researching', 'contacted', 'replied', 'discovery', 'qualified', 'converted', 'lost')) not valid;
update public.leads set status = case status
  when 'in_progress' then 'contacted'
  when 'won' then 'converted'
  when 'spam' then 'lost'
  else status end;
alter table public.leads validate constraint leads_status_check;
alter table public.leads drop constraint if exists leads_score_check;
alter table public.leads add constraint leads_score_check check (
  (lead_score is null or lead_score between 0 and 10)
  and (digital_maturity is null or digital_maturity between 0 and 10)
  and (pain_score is null or pain_score between 0 and 10)
  and (ability_to_pay is null or ability_to_pay between 0 and 10)
  and (willingness_to_pay is null or willingness_to_pay between 0 and 10)
  and (urgency_score is null or urgency_score between 0 and 10)
  and (reachability_score is null or reachability_score between 0 and 10)
) not valid;
alter table public.leads validate constraint leads_score_check;

alter table public.tasks drop constraint if exists tasks_status_check;
alter table public.tasks add constraint tasks_status_check
  check (status in ('todo', 'in_progress', 'blocked', 'waiting', 'done', 'cancelled')) not valid;
alter table public.tasks validate constraint tasks_status_check;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'leads_estimated_value_nonnegative'
      and conrelid = 'public.leads'::regclass
  ) then
    alter table public.leads
      add constraint leads_estimated_value_nonnegative
      check (estimated_value is null or estimated_value >= 0) not valid;
    alter table public.leads validate constraint leads_estimated_value_nonnegative;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'leads_currency_format'
      and conrelid = 'public.leads'::regclass
  ) then
    alter table public.leads
      add constraint leads_currency_format check (currency ~ '^[A-Z]{3}$') not valid;
    alter table public.leads validate constraint leads_currency_format;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'tasks_estimated_minutes_positive'
      and conrelid = 'public.tasks'::regclass
  ) then
    alter table public.tasks
      add constraint tasks_estimated_minutes_positive
      check (estimated_minutes is null or estimated_minutes > 0) not valid;
    alter table public.tasks validate constraint tasks_estimated_minutes_positive;
  end if;
end;
$$;

create unique index if not exists leads_converted_deal_uidx
  on public.leads(converted_deal_id) where converted_deal_id is not null;
create index if not exists leads_company_idx on public.leads(company_id) where company_id is not null;
create index if not exists tasks_client_project_status_idx
  on public.tasks(client_project_id, status) where client_project_id is not null;
create index if not exists tasks_deal_idx on public.tasks(deal_id) where deal_id is not null;
create index if not exists companies_status_owner_idx on public.companies(status, owner_id);
create index if not exists companies_name_idx on public.companies(lower(name));
create index if not exists contacts_company_idx on public.contacts(company_id, is_primary desc);
create index if not exists contacts_email_idx on public.contacts(lower(email)) where email is not null;
create index if not exists products_active_idx on public.products(active, kind);
create index if not exists deals_stage_owner_idx on public.deals(stage, owner_id);
create index if not exists deals_company_idx on public.deals(company_id, updated_at desc);
create index if not exists deals_product_idx on public.deals(product_id);
create index if not exists deals_next_action_idx on public.deals(next_action_date) where status = 'open';
create index if not exists deals_expected_close_idx
  on public.deals(expected_close_date) where status = 'open';
create index if not exists client_projects_status_owner_idx
  on public.client_projects(status, owner_id);
create index if not exists client_projects_company_idx
  on public.client_projects(company_id, updated_at desc);
create index if not exists client_projects_target_idx
  on public.client_projects(target_date) where status not in ('completed', 'cancelled');
create index if not exists project_milestones_project_due_idx
  on public.project_milestones(project_id, due_date);
create index if not exists invoices_company_status_idx on public.invoices(company_id, status);
create index if not exists invoices_due_idx
  on public.invoices(due_date) where status in ('sent', 'partially_paid', 'overdue');
create index if not exists invoice_items_invoice_idx on public.invoice_items(invoice_id, sort_order);
create index if not exists payments_invoice_idx on public.payments(invoice_id, paid_at desc);
create index if not exists payments_company_idx on public.payments(company_id, created_at desc);
create index if not exists subscriptions_company_status_idx
  on public.subscriptions(company_id, status);
create index if not exists subscriptions_next_billing_idx
  on public.subscriptions(next_billing_date) where status in ('trialing', 'active', 'past_due');
create index if not exists activities_company_time_idx
  on public.activities(company_id, occurred_at desc) where company_id is not null;
create index if not exists activities_deal_time_idx
  on public.activities(deal_id, occurred_at desc) where deal_id is not null;
create index if not exists activities_project_time_idx
  on public.activities(project_id, occurred_at desc) where project_id is not null;
create index if not exists notes_company_idx on public.notes(company_id, created_at desc);
create index if not exists notes_deal_idx on public.notes(deal_id, created_at desc);
create index if not exists notes_project_idx on public.notes(project_id, created_at desc);
create index if not exists attachments_company_idx on public.attachments(company_id, created_at desc);
create index if not exists attachments_deal_idx on public.attachments(deal_id, created_at desc);
create index if not exists attachments_project_idx on public.attachments(project_id, created_at desc);
create index if not exists leads_next_follow_up_idx
  on public.leads(next_follow_up_at) where status not in ('converted', 'lost');

create or replace function public.hq_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'companies', 'contacts', 'products', 'deals', 'client_projects',
    'project_milestones', 'invoices', 'payments', 'subscriptions', 'notes'
  ]
  loop
    execute format('drop trigger if exists hq_set_updated_at on public.%I', table_name);
    execute format(
      'create trigger hq_set_updated_at before update on public.%I
       for each row execute function public.hq_set_updated_at()',
      table_name
    );
  end loop;
end;
$$;

create or replace function public.prevent_activity_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  -- Permit nested FK actions while rejecting direct edits/deletes.
  if pg_trigger_depth() > 1 then
    if tg_op = 'UPDATE' then
      return new;
    end if;
    return old;
  end if;
  raise exception 'activities is append-only';
end;
$$;

drop trigger if exists activities_append_only on public.activities;
create trigger activities_append_only
before update or delete on public.activities
for each row execute function public.prevent_activity_mutation();

create or replace function public.convert_lead_to_deal(
  p_lead_id uuid,
  p_actor_id uuid default null,
  p_title text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  source_lead public.leads%rowtype;
  company_uuid uuid;
  contact_uuid uuid;
  deal_uuid uuid;
begin
  select * into source_lead
  from public.leads
  where id = p_lead_id
  for update;

  if not found then
    raise exception 'Lead % not found', p_lead_id using errcode = 'P0002';
  end if;

  if source_lead.converted_deal_id is not null then
    return source_lead.converted_deal_id;
  end if;

  company_uuid := source_lead.company_id;
  if company_uuid is null and nullif(btrim(coalesce(source_lead.business_name, '')), '') is not null then
    insert into public.companies (name, email, website, owner_id, created_by, metadata)
    values (
      btrim(source_lead.business_name),
      source_lead.email,
      source_lead.site_url,
      source_lead.assignee_id,
      p_actor_id,
      jsonb_build_object('source_lead_id', source_lead.id)
    )
    returning id into company_uuid;
  end if;

  contact_uuid := source_lead.contact_id;
  if contact_uuid is null and (
    nullif(btrim(coalesce(source_lead.full_name, '')), '') is not null
    or nullif(btrim(coalesce(source_lead.email, '')), '') is not null
  ) then
    insert into public.contacts (
      company_id, first_name, email, is_primary, created_by, metadata
    )
    values (
      company_uuid,
      nullif(btrim(source_lead.full_name), ''),
      source_lead.email,
      true,
      p_actor_id,
      jsonb_build_object('source_lead_id', source_lead.id)
    )
    returning id into contact_uuid;
  end if;

  insert into public.deals (
    company_id, primary_contact_id, lead_id, title, value, currency,
    owner_id, source, notes, created_by, metadata
  )
  values (
    company_uuid,
    contact_uuid,
    source_lead.id,
    coalesce(
      nullif(btrim(p_title), ''),
      nullif(btrim(source_lead.business_name), ''),
      nullif(btrim(source_lead.full_name), ''),
      'Lead ' || source_lead.id::text
    ),
    coalesce(source_lead.estimated_value, 0),
    source_lead.currency,
    source_lead.assignee_id,
    source_lead.source,
    source_lead.brief,
    p_actor_id,
    jsonb_build_object('source_lead_id', source_lead.id)
  )
  returning id into deal_uuid;

  update public.leads
  set company_id = company_uuid,
      contact_id = contact_uuid,
      converted_deal_id = deal_uuid,
      converted_at = now(),
      status = 'converted',
      updated_at = now()
  where id = source_lead.id;

  insert into public.activities (
    activity_type, subject, company_id, contact_id, deal_id, lead_id, actor_id, metadata
  )
  values (
    'system', 'Lead converted to deal', company_uuid, contact_uuid,
    deal_uuid, source_lead.id, p_actor_id, jsonb_build_object('conversion', 'lead_to_deal')
  );

  return deal_uuid;
end;
$$;

create or replace function public.convert_won_deal_to_project(
  p_deal_id uuid,
  p_actor_id uuid default null,
  p_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  source_deal public.deals%rowtype;
  existing_project_id uuid;
  project_uuid uuid;
begin
  select * into source_deal
  from public.deals
  where id = p_deal_id
  for update;

  if not found then
    raise exception 'Deal % not found', p_deal_id using errcode = 'P0002';
  end if;

  select id into existing_project_id
  from public.client_projects
  where deal_id = source_deal.id;

  if existing_project_id is not null then
    return existing_project_id;
  end if;

  if source_deal.status <> 'won' or source_deal.stage <> 'won' then
    raise exception 'Deal % must be won before project conversion', p_deal_id
      using errcode = '23514';
  end if;

  insert into public.client_projects (
    deal_id, company_id, primary_contact_id, product_id, name, status, owner_id,
    start_date, budget, sold_price, currency, description, created_by, metadata
  )
  values (
    source_deal.id,
    source_deal.company_id,
    source_deal.primary_contact_id,
    source_deal.product_id,
    coalesce(nullif(btrim(p_name), ''), source_deal.title),
    'planned',
    source_deal.owner_id,
    current_date,
    source_deal.value,
    source_deal.value,
    source_deal.currency,
    source_deal.notes,
    p_actor_id,
    jsonb_build_object('source_deal_id', source_deal.id)
  )
  returning id into project_uuid;

  insert into public.activities (
    activity_type, subject, company_id, contact_id, deal_id, project_id, actor_id, metadata
  )
  values (
    'system', 'Won deal converted to project', source_deal.company_id,
    source_deal.primary_contact_id, source_deal.id, project_uuid, p_actor_id,
    jsonb_build_object('conversion', 'won_deal_to_project')
  );

  return project_uuid;
end;
$$;

create or replace function public.hq_dashboard_summary(
  p_from date default date_trunc('month', current_date)::date,
  p_to date default current_date
)
returns jsonb
language sql
stable
set search_path = public
as $$
  with params as (
    select least(p_from, p_to) as date_from, greatest(p_from, p_to) as date_to
  ),
  pipeline as (
    select
      count(*) filter (where d.status = 'open')::bigint as open_deals,
      coalesce(sum(d.value) filter (where d.status = 'open'), 0)::numeric as pipeline_value,
      coalesce(
        sum(d.value * d.probability::numeric / 100) filter (where d.status = 'open'),
        0
      )::numeric as weighted_pipeline,
      coalesce(
        sum(d.value) filter (
          where d.status = 'won'
            and d.closed_at::date between p.date_from and p.date_to
        ),
        0
      )::numeric as won_value
    from public.deals d cross join params p
  ),
  delivery as (
    select
      count(*) filter (where status in ('planned', 'discovery', 'design', 'development', 'testing', 'waiting_client', 'launch', 'paused'))::bigint as open_projects,
      count(*) filter (where health in ('yellow', 'red'))::bigint as unhealthy_projects,
      count(*) filter (
        where target_date < current_date and status not in ('completed', 'cancelled')
      )::bigint as overdue_projects
    from public.client_projects
  ),
  finance as (
    select
      coalesce(sum(total), 0)::numeric as invoiced_value,
      coalesce(sum(amount_paid), 0)::numeric as invoice_paid_value,
      coalesce(sum(total - amount_paid) filter (
        where status in ('sent', 'partially_paid', 'overdue')
      ), 0)::numeric as receivables
    from public.invoices i cross join params p
    where i.issue_date between p.date_from and p.date_to
  ),
  cash as (
    select coalesce(sum(amount) filter (where status = 'succeeded'), 0)::numeric as cash_collected
    from public.payments pay cross join params p
    where pay.paid_at::date between p.date_from and p.date_to
  ),
  recurring as (
    select coalesce(sum(
      case s.interval
        when 'week' then s.amount * 52 / (12 * s.interval_count)
        when 'month' then s.amount / s.interval_count
        when 'quarter' then s.amount / (3 * s.interval_count)
        when 'year' then s.amount / (12 * s.interval_count)
      end
    ) filter (where s.status in ('trialing', 'active', 'past_due')), 0)::numeric as mrr
    from public.subscriptions s
  )
  select jsonb_build_object(
    'from', p.date_from,
    'to', p.date_to,
    'openDeals', pipeline.open_deals,
    'pipelineValue', pipeline.pipeline_value,
    'weightedPipeline', pipeline.weighted_pipeline,
    'wonValue', pipeline.won_value,
    'openProjects', delivery.open_projects,
    'unhealthyProjects', delivery.unhealthy_projects,
    'overdueProjects', delivery.overdue_projects,
    'invoicedValue', finance.invoiced_value,
    'invoicePaidValue', finance.invoice_paid_value,
    'receivables', finance.receivables,
    'cashCollected', cash.cash_collected,
    'mrr', recurring.mrr
  )
  from params p
  cross join pipeline
  cross join delivery
  cross join finance
  cross join cash
  cross join recurring;
$$;

create or replace function public.record_invoice_payment(
  p_invoice_id uuid,
  p_amount numeric,
  p_currency text,
  p_method text default null,
  p_external_reference text default null,
  p_paid_at timestamptz default now(),
  p_metadata jsonb default '{}'::jsonb,
  p_created_by uuid default null
)
returns public.payments
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  source_invoice public.invoices%rowtype;
  payment_row public.payments%rowtype;
  next_paid numeric(14,2);
begin
  if p_amount <= 0 then
    raise exception 'Payment amount must be positive' using errcode = '23514';
  end if;

  select * into source_invoice from public.invoices
  where id = p_invoice_id for update;
  if not found then
    raise exception 'Invoice % not found', p_invoice_id using errcode = 'P0002';
  end if;
  if source_invoice.status in ('cancelled', 'void') then
    raise exception 'Cancelled invoice cannot receive payments' using errcode = '23514';
  end if;
  if upper(p_currency) <> source_invoice.currency then
    raise exception 'Payment currency must match invoice currency' using errcode = '23514';
  end if;
  if p_amount > source_invoice.total - source_invoice.amount_paid then
    raise exception 'Payment exceeds invoice outstanding amount' using errcode = '23514';
  end if;

  insert into public.payments (
    invoice_id, company_id, amount, currency, status, method,
    external_reference, paid_at, metadata, created_by
  ) values (
    source_invoice.id, source_invoice.company_id, p_amount, source_invoice.currency,
    'succeeded', p_method, p_external_reference, coalesce(p_paid_at, now()),
    coalesce(p_metadata, '{}'::jsonb), p_created_by
  ) returning * into payment_row;

  next_paid := source_invoice.amount_paid + p_amount;
  update public.invoices
  set amount_paid = next_paid,
      status = case when next_paid >= total then 'paid' else 'partially_paid' end,
      updated_at = now()
  where id = source_invoice.id;

  insert into public.activities (
    activity_type, subject, body, company_id, actor_id, occurred_at, metadata
  ) values (
    'system', 'Payment received', source_invoice.invoice_number,
    source_invoice.company_id, p_created_by, coalesce(p_paid_at, now()),
    jsonb_build_object('invoiceId', source_invoice.id, 'paymentId', payment_row.id, 'amount', p_amount)
  );

  return payment_row;
end;
$$;

revoke all on function public.convert_lead_to_deal(uuid, uuid, text) from public;
revoke all on function public.convert_won_deal_to_project(uuid, uuid, text) from public;
revoke all on function public.hq_dashboard_summary(date, date) from public;
revoke all on function public.record_invoice_payment(uuid, numeric, text, text, text, timestamptz, jsonb, uuid) from public;
grant execute on function public.convert_lead_to_deal(uuid, uuid, text) to service_role;
grant execute on function public.convert_won_deal_to_project(uuid, uuid, text) to service_role;
grant execute on function public.hq_dashboard_summary(date, date) to authenticated, service_role;
grant execute on function public.record_invoice_payment(uuid, numeric, text, text, text, timestamptz, jsonb, uuid) to service_role;

alter table public.companies enable row level security;
alter table public.contacts enable row level security;
alter table public.products enable row level security;
alter table public.deals enable row level security;
alter table public.client_projects enable row level security;
alter table public.project_milestones enable row level security;
alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;
alter table public.payments enable row level security;
alter table public.subscriptions enable row level security;
alter table public.activities enable row level security;
alter table public.notes enable row level security;
alter table public.attachments enable row level security;

-- HQ tables intentionally have no anonymous policies. Studio APIs authenticate,
-- authorize capabilities, and use the server-only service client.
